openapi: 3.0.0
info:
  title: Space Marine API
  version: 1.0.0
tags:
  - name: Space Marines
    description: Операции с десантниками
  - name: Space Utils
    description: Утилитарные операции с десантниками
paths:
  /space-marines:
    get:
      summary: Получить всех десантников
      parameters:
        - name: page
          in: query
          description: Номер страницы
          schema:
            type: integer
            minimum: 1
        - name: pageSize
          in: query
          description: Размер страницы
          schema:
            type: integer
            minimum: 1
        - name: name
          in: query
          description: Фильтр по имени
          schema:
            type: string
        - name: health
          in: query
          description: Фильтр по здоровью
          schema:
            type: integer
            minimum: 1
        - name: achievements
          in: query
          description: Фильтр по достижениям
          schema:
            type: string
        - name: category
          in: query
          description: Фильтр по категории
          schema:
            $ref: '#/components/schemas/AstartesCategory'
        - name: weaponType
          in: query
          description: Фильтр по типу оружия
          schema:
            $ref: '#/components/schemas/Weapon'
        - name: chapterName
          in: query
          description: Фильтр по имени главы
          schema:
            type: string
        - name: chapterWorld
          in: query
          description: Фильтр по миру главы
          schema:
            type: string
        - name: creationDate
          in: query
          description: Фильтр по дате создания
          schema:
            type: string
            format: date-time
        - name: coordinatesX
          in: query
          description: Фильтр по координате X
          schema:
            type: number
            format: double
            maximum: 872
        - name: coordinatesY
          in: query
          description: Фильтр по координате Y
          schema:
            type: integer
            format: int64
            maximum: 110
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpaceMarine'
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Marines
    post:
      summary: Добавить нового десантника
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '204':
          description: Десантник успешно создан
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Marines
  /space-marines/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          minimum: 1
        description: ID десантника
    get:
      summary: Получить десантника по ID
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Marines
    put:
      summary: Обновить десантника
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '204':
          description: Успех
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Marines
    delete:
      summary: Удалить десантника
      responses:
        '204':
          description: Успех
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Marines
  /space-utils/min-name:
    get:
      summary: Получить десантника с минимальным значением поля name
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Utils
  /space-utils/max-category:
    get:
      summary: Получить десантника с максимальным значением поля category
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Utils
  /space-utils/sum-health:
    get:
      summary: Рассчитать сумму значений поля health для всех всех десантников
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: object
                properties:
                  sumHealth:
                    type: integer
        default:
          description: Возвращает тело для ошибки (код ошибки, время и сообщение)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
          - Space Utils
components:
  schemas:
    SpaceMarine:
      type: object
      required:
        - id
        - name
        - coordinates
        - creationDate
        - achievements
        - category
        - chapter
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
        health:
          type: integer
          format: int64
          minimum: 1
        achievements:
          type: string
        category:
          $ref: '#/components/schemas/AstartesCategory'
        weaponType:
          $ref: '#/components/schemas/Weapon'
        chapter:
          $ref: '#/components/schemas/Chapter'
    Coordinates:
      type: object
      properties:
        x:
          type: number
          format: double
          maximum: 872
        y:
          type: integer
          format: int64
          maximum: 110
    Chapter:
      type: object
      required:
        - name
        - world
      properties:
        name:
          type: string
          minLength: 1
        world:
          type: string
    AstartesCategory:
      type: string
      enum:
        - SCOUT
        - AGGRESSOR
        - TACTICAL
        - LIBRARIAN
        - APOTHECARY
    Weapon:
      type: string
      enum:
        - BOLTGUN
        - HEAVY_BOLTGUN
        - PLASMA_GUN
        - GRAV_GUN
    Starship:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        spaceMarine:
          type: array
          items:
            $ref: '#/components/schemas/SpaceMarine'
        name:
          type: string
          example: RosKosmos
        width: 
          type: integer
          maximum: 532
        height: 
          type: integer
          maximum: 9987

    Error:
      type: object
      required:
        - httpCode
        - message
        - time
      properties:
        code:
          type: integer
          format: int32
          example: 404
        message:
          type: string
          example: Not Found
        time:
          type: string
          format: date-time
          example: 2023-09-13T00:00:090Z